"""Postgres RLS for the phase-5 web tables — runs only with POSTGRES_TEST_URL.

Mirrors migrations 022/023: ``onboarding_items`` and ``queued_reminders`` are
owner-scoped within a household (decision D3), so a row is visible/writable only
when ``household_id = current_setting('app.current_household')`` **and**
``owner_user_id = current_setting('app.current_user')``. FORCE ROW LEVEL SECURITY
applies to the table owner too, so a non-superuser role is required (a superuser
bypasses RLS — see tests/conftest_postgres.py). Skips unless POSTGRES_TEST_URL is
set.
"""

from __future__ import annotations

from collections.abc import Iterator
import contextlib
import os
import uuid

import pytest
import sqlalchemy as sa
from sqlalchemy.orm import Session, sessionmaker

pytestmark = pytest.mark.postgres

# Two households; HH_A has two members (A1, A2) to prove owner-scoping within a
# household; HH_B is a separate household.
HH_A, HH_B = uuid.uuid4(), uuid.uuid4()
A1, A2, B1 = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()

_DDL = [
    """CREATE TABLE onboarding_items (
        id uuid PRIMARY KEY,
        household_id uuid NOT NULL,
        owner_user_id uuid NOT NULL,
        item_key varchar NOT NULL,
        status varchar NOT NULL DEFAULT 'pending',
        trigger_state json NOT NULL DEFAULT '{}',
        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (owner_user_id, item_key)
    )""",
    """CREATE TABLE queued_reminders (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id varchar NOT NULL,
        kind varchar NOT NULL,
        content text NOT NULL,
        household_id uuid NOT NULL,
        owner_user_id uuid NOT NULL,
        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (conversation_id, kind)
    )""",
]
_PREDICATE = (
    "household_id = current_setting('app.current_household', true)::uuid "
    "AND owner_user_id = current_setting('app.current_user', true)::uuid"
)
_TABLES = ("onboarding_items", "queued_reminders")


@pytest.fixture
def pg_web() -> Iterator[sessionmaker[Session]]:
    url = os.environ.get("POSTGRES_TEST_URL", "").strip()
    if not url:
        pytest.skip("POSTGRES_TEST_URL not set")
    schema = f"tw_{uuid.uuid4().hex[:8]}"
    admin = sa.create_engine(url)
    with admin.begin() as c:
        c.execute(sa.text(f'CREATE SCHEMA "{schema}"'))
    sep = "&" if "?" in url else "?"
    engine = sa.create_engine(f"{url}{sep}options=-csearch_path%3D{schema}")
    with engine.begin() as c:
        for ddl in _DDL:
            c.execute(sa.text(ddl))
        for table in _TABLES:
            c.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
            c.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
            c.execute(
                sa.text(
                    f"CREATE POLICY tenant_isolation ON {table} "
                    f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
                )
            )
    yield sessionmaker(bind=engine)
    engine.dispose()
    with admin.begin() as c:
        c.execute(sa.text(f'DROP SCHEMA "{schema}" CASCADE'))
    admin.dispose()


@contextlib.contextmanager
def _as(
    factory: sessionmaker[Session], household: uuid.UUID, user: uuid.UUID
) -> Iterator[Session]:
    s = factory()
    try:
        s.execute(
            sa.text(
                "SELECT set_config('app.current_household', :h, true), "
                "set_config('app.current_user', :u, true)"
            ),
            {"h": str(household), "u": str(user)},
        )
        yield s
        s.commit()
    except Exception:
        s.rollback()
        raise
    finally:
        s.close()


def _seed_reminders(factory: sessionmaker[Session]) -> None:
    with _as(factory, HH_A, A1) as s:
        s.execute(
            sa.text(
                "INSERT INTO queued_reminders (conversation_id, kind, content, "
                "household_id, owner_user_id) VALUES ('c1', 'onboarding', 'a', :h, :u)"
            ),
            {"h": str(HH_A), "u": str(A1)},
        )
    with _as(factory, HH_B, B1) as s:
        s.execute(
            sa.text(
                "INSERT INTO queued_reminders (conversation_id, kind, content, "
                "household_id, owner_user_id) VALUES ('c2', 'onboarding', 'b', :h, :u)"
            ),
            {"h": str(HH_B), "u": str(B1)},
        )


def test_queued_reminders_cross_household_invisible(pg_web) -> None:
    _seed_reminders(pg_web)
    # B's principal sees only its own household's reminders, none of A's.
    with _as(pg_web, HH_B, B1) as s:
        rows = s.execute(sa.text("SELECT household_id FROM queued_reminders")).all()
    assert rows and all(r[0] == HH_B for r in rows)
    assert not any(r[0] == HH_A for r in rows)


def test_onboarding_items_owner_scoped(pg_web) -> None:
    # A1 and A2 are in the SAME household; A2 must not read A1's items.
    with _as(pg_web, HH_A, A1) as s:
        s.execute(
            sa.text(
                "INSERT INTO onboarding_items (id, household_id, owner_user_id, item_key) "
                "VALUES (:i, :h, :u, 'connect_plaid')"
            ),
            {"i": str(uuid.uuid4()), "h": str(HH_A), "u": str(A1)},
        )
    with _as(pg_web, HH_A, A2) as s:
        rows = s.execute(sa.text("SELECT owner_user_id FROM onboarding_items")).all()
    assert not any(r[0] == A1 for r in rows)


def test_with_check_blocks_foreign_household_reminder(pg_web) -> None:
    # A's session tries to insert a reminder stamped with B's household → WITH
    # CHECK rejects it.
    with pytest.raises(sa.exc.DBAPIError):
        with _as(pg_web, HH_A, A1) as s:
            s.execute(
                sa.text(
                    "INSERT INTO queued_reminders (conversation_id, kind, content, "
                    "household_id, owner_user_id) VALUES ('c3', 'onboarding', 'x', :h, :u)"
                ),
                {"h": str(HH_B), "u": str(A1)},  # foreign household
            )
            s.flush()
