"""Add the web ``user_credentials`` vault table with owner-scoped RLS

Revision ID: 020_add_user_credentials
Revises: 019_add_conversation_tenancy
Create Date: 2026-07-04

Phase 2b: the encrypted per-user BYO-credential vault. The table lives in the
dedicated ``web`` schema (website persistence, same Postgres server as finance —
see ``penny.api.persistence.engine``), so — like the phase-2 conversation tables
— it is create_all-managed and this revision layers the RLS on top.

Unlike the finance/household policy, ``user_credentials`` is **owner-scoped**: a
credential is private to its ``user_id`` even within a household (no shared arm),
so the ``tenant_isolation`` policy keys purely on
``user_id = current_setting('app.current_user')`` — the GUC the billing web
session binds to the *real* user id (never the joint nil sentinel). USING **and**
WITH CHECK + FORCE fence reads and writes, including the app role.

SQLite dev/tests skip this entirely: the table comes from the model via
``create_all`` and the vault's ``user_id`` filter is the tenant layer there.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020_add_user_credentials"
down_revision: str | Sequence[str] | None = "019_add_conversation_tenancy"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "web.user_credentials"
# Owner-private: match the session's real user; no household/shared arm.
_PREDICATE = "user_id = current_setting('app.current_user', true)::uuid"


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("CREATE SCHEMA IF NOT EXISTS web")
    # Defensive create (create_all normally owns web-table creation): keep the
    # pure-migration path working without depending on startup ordering.
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_TABLE} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id uuid NOT NULL,
            provider varchar NOT NULL,
            kind varchar NOT NULL,
            secret_ciphertext varchar NOT NULL,
            meta json NOT NULL DEFAULT '{{}}',
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_user_credentials_user_provider UNIQUE (user_id, provider)
        )
        """
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS ix_user_credentials_user_id ON {_TABLE} (user_id)"
    )
    op.execute(f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {_TABLE} "
        f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
    )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_TABLE}")
    op.execute(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY")
    op.execute(f"DROP TABLE IF EXISTS {_TABLE}")
