"""Add the web ``usage_events`` + ``user_billing`` tables with owner-scoped RLS

Revision ID: 021_add_usage_events_and_user_billing
Revises: 020_add_user_credentials
Create Date: 2026-07-04

Phase 2b: the subsidy-metering ledger (``usage_events``, one row per subsidized
completion) and the per-user subsidy record (``user_billing``). Both live in the
``web`` schema and — like migration 020 / the phase-2 conversation tables — are
create_all-managed, so this revision layers owner-scoped RLS on top: the
``tenant_isolation`` policy keys purely on
``user_id = current_setting('app.current_user')`` (the real user, never the joint
nil sentinel), USING + WITH CHECK + FORCE.

SQLite dev/tests skip this entirely (Postgres-guarded); the tables come from the
models via ``create_all`` and the metering store's ``user_id`` filter is the
tenant layer there.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "021_add_usage_events_and_user_billing"
down_revision: str | Sequence[str] | None = "020_add_user_credentials"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREDICATE = "user_id = current_setting('app.current_user', true)::uuid"
_TABLES = ("web.usage_events", "web.user_billing")


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("CREATE SCHEMA IF NOT EXISTS web")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS web.usage_events (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id uuid NOT NULL,
            model varchar NOT NULL,
            input_tokens integer NOT NULL DEFAULT 0,
            output_tokens integer NOT NULL DEFAULT 0,
            cache_tokens integer NOT NULL DEFAULT 0,
            cost_cents integer NOT NULL DEFAULT 0,
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_usage_events_user_id "
        "ON web.usage_events (user_id)"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS web.user_billing (
            user_id uuid PRIMARY KEY,
            subsidy_granted_cents integer NOT NULL DEFAULT 0,
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for table in _TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
        op.execute(f"DROP TABLE IF EXISTS {table}")
