"""Add the web ``queued_reminders`` table with owner-scoped RLS

Revision ID: 023_add_queued_reminders
Revises: 022_add_onboarding_items
Create Date: 2026-07-04

Phase 5: the DB-backed reminder queue. A reminder enqueued from one HTTP request
(e.g. the Plaid exchange endpoint) is drained into the next agent turn's user
message by the harness. It is website/app state, so — like the phase-2/2b web
tables — it lives in the dedicated ``web`` schema (out of the agent ``run_sql``
blast radius) and is create_all-managed; this revision layers the RLS on top.

Owner-scoped within a household (decision D3): a reminder is private to its
``owner_user_id`` even in a shared household (no joint arm), so
``tenant_isolation`` keys on ``household_id`` **and** ``owner_user_id`` against
the ``app.current_household`` / ``app.current_user`` GUCs the owner-scoped web
session binds (``penny.api.persistence.tenant``). USING **and** WITH CHECK +
FORCE fence reads and writes, including the app role.

SQLite dev/tests skip this entirely: the table comes from the model via
``create_all`` and the queue's ``household_id`` + ``owner_user_id`` filter is the
tenant layer there.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "023_add_queued_reminders"
down_revision: str | Sequence[str] | None = "022_add_onboarding_items"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "web.queued_reminders"
_PREDICATE = (
    "household_id = current_setting('app.current_household', true)::uuid "
    "AND owner_user_id = current_setting('app.current_user', true)::uuid"
)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("CREATE SCHEMA IF NOT EXISTS web")
    # Defensive create (create_all normally owns web-table creation): keep the
    # pure-migration path working without depending on startup ordering.
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_TABLE} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            conversation_id varchar NOT NULL,
            kind varchar NOT NULL,
            content text NOT NULL,
            household_id uuid NOT NULL,
            owner_user_id uuid NOT NULL,
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_queued_reminders_conv_kind UNIQUE (conversation_id, kind)
        )
        """
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS ix_queued_reminders_conversation_id "
        f"ON {_TABLE} (conversation_id)"
    )
    op.execute(f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {_TABLE} "
        f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
    )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_TABLE}")
    op.execute(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY")
    op.execute(f"DROP TABLE IF EXISTS {_TABLE}")
