"""Postgres owner-scoped RLS for the billing tables — runs only with POSTGRES_TEST_URL.

Mirrors migrations 020/021: the web ``user_credentials`` / ``usage_events`` /
``user_billing`` tables are owner-scoped, so a row is visible/writable only when
``user_id = current_setting('app.current_user')``. FORCE ROW LEVEL SECURITY
applies to the table owner too, so a non-superuser role is required (a superuser
bypasses RLS — see tests/conftest_postgres.py). Skips unless POSTGRES_TEST_URL is
set.
"""

from __future__ import annotations

from collections.abc import Iterator
import contextlib
import os
import uuid

import pytest
import sqlalchemy as sa
from sqlalchemy.orm import Session, sessionmaker

pytestmark = pytest.mark.postgres

UA, UB = uuid.uuid4(), uuid.uuid4()

_DDL = [
    """CREATE TABLE user_credentials (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id uuid NOT NULL,
        provider varchar NOT NULL,
        kind varchar NOT NULL,
        secret_ciphertext varchar NOT NULL,
        meta json NOT NULL DEFAULT '{}',
        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (user_id, provider)
    )""",
    """CREATE TABLE usage_events (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id uuid NOT NULL,
        model varchar NOT NULL,
        input_tokens integer NOT NULL DEFAULT 0,
        output_tokens integer NOT NULL DEFAULT 0,
        cache_tokens integer NOT NULL DEFAULT 0,
        cost_cents integer NOT NULL DEFAULT 0,
        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""",
    """CREATE TABLE user_billing (
        user_id uuid PRIMARY KEY,
        subsidy_granted_cents integer NOT NULL DEFAULT 0,
        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""",
]
_PREDICATE = "user_id = current_setting('app.current_user', true)::uuid"
_TABLES = ("user_credentials", "usage_events", "user_billing")


@pytest.fixture
def pg_billing() -> Iterator[sessionmaker[Session]]:
    url = os.environ.get("POSTGRES_TEST_URL", "").strip()
    if not url:
        pytest.skip("POSTGRES_TEST_URL not set")
    schema = f"tb_{uuid.uuid4().hex[:8]}"
    admin = sa.create_engine(url)
    with admin.begin() as c:
        c.execute(sa.text(f'CREATE SCHEMA "{schema}"'))
    sep = "&" if "?" in url else "?"
    engine = sa.create_engine(f"{url}{sep}options=-csearch_path%3D{schema}")
    with engine.begin() as c:
        for ddl in _DDL:
            c.execute(sa.text(ddl))
        for table in _TABLES:
            c.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
            c.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
            c.execute(
                sa.text(
                    f"CREATE POLICY tenant_isolation ON {table} "
                    f"USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
                )
            )
    yield sessionmaker(bind=engine)
    engine.dispose()
    with admin.begin() as c:
        c.execute(sa.text(f'DROP SCHEMA "{schema}" CASCADE'))
    admin.dispose()


@contextlib.contextmanager
def _as_user(factory: sessionmaker[Session], user: uuid.UUID) -> Iterator[Session]:
    s = factory()
    try:
        s.execute(
            sa.text("SELECT set_config('app.current_user', :u, true)"),
            {"u": str(user)},
        )
        yield s
        s.commit()
    except Exception:
        s.rollback()
        raise
    finally:
        s.close()


def _seed(factory: sessionmaker[Session]) -> None:
    with _as_user(factory, UA) as s:
        s.execute(
            sa.text(
                "INSERT INTO user_credentials (user_id, provider, kind, secret_ciphertext) "
                "VALUES (:u, 'google', 'api_key', 'v1:cipher-a')"
            ),
            {"u": str(UA)},
        )
        s.execute(
            sa.text(
                "INSERT INTO usage_events (user_id, model, cost_cents) "
                "VALUES (:u, 'm', 10)"
            ),
            {"u": str(UA)},
        )
        s.execute(
            sa.text(
                "INSERT INTO user_billing (user_id, subsidy_granted_cents) VALUES (:u, 200)"
            ),
            {"u": str(UA)},
        )
    with _as_user(factory, UB) as s:
        s.execute(
            sa.text(
                "INSERT INTO user_credentials (user_id, provider, kind, secret_ciphertext) "
                "VALUES (:u, 'google', 'api_key', 'v1:cipher-b')"
            ),
            {"u": str(UB)},
        )


@pytest.mark.parametrize("table", _TABLES)
def test_user_b_sees_none_of_user_a_rows(pg_billing, table: str) -> None:
    _seed(pg_billing)
    with _as_user(pg_billing, UB) as s:
        rows = s.execute(
            sa.text(f"SELECT user_id FROM {table}")  # noqa: S608 - table from a fixed allowlist
        ).all()
    assert all(r[0] == UB for r in rows)
    # None of A's rows leak into B's view.
    assert not any(r[0] == UA for r in rows)


def test_user_a_sees_only_own_credential(pg_billing) -> None:
    _seed(pg_billing)
    with _as_user(pg_billing, UA) as s:
        rows = s.execute(
            sa.text("SELECT secret_ciphertext FROM user_credentials")
        ).all()
    assert {r[0] for r in rows} == {"v1:cipher-a"}


def test_write_into_another_users_row_is_rejected(pg_billing) -> None:
    with pytest.raises(sa.exc.DBAPIError):  # WITH CHECK violation
        with _as_user(pg_billing, UA) as s:
            s.execute(
                sa.text(
                    "INSERT INTO user_billing (user_id, subsidy_granted_cents) "
                    "VALUES (:u, 999)"
                ),
                {"u": str(UB)},  # A tries to write a row owned by B
            )
            s.flush()
